### ISSUE TITLE
1486498922: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".

### ISSUE THREAD

**Issue by Vishal1419** [jpmens/mosquitto-auth-plug#197]
I know that there are many questions on the issue I am submitting and most of them are solved.
Please read my question in some detail before marking it as duplicate:

I am trying to run the command as shown below:
/usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf

Here is the error that I am getting:
1486498922: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".

The commands from installation of mosquitto to the error are given below:

- wget http://mosquitto.org/files/source/mosquitto-1.3.5.tar.gz //download mosquitto-1.3.5
- tar xvzf mosquitto-1.3.5.tar.gz //unzip tar file
- cd mosquitto-1.3.5
- nano config.mk
- Ctrl+W //search
    Find SRV
- WITH_SRV:= no
- Ctrl+O + Enter //save
- Ctrl+X //Exit out of file
- cd
- wget http://www.openssl.org/source/openssl-1.1.0c.tar.gz
- tar -xvzf openssl-1.1.0c.tar.gz //unzip the tar file
- cd openssl-1.1.0c
- ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl
- make
- sudo make install_sw
- cd
- cd mosquitto-1.3.5
- sudo apt-get install libssl-dev
- sudo make
- sudo make install
- git clone https://github.com/jpmens/mosquitto-auth-plug.git
- git clone https://github.com/redis/hiredis.git
- cd hiredis
- make
- sudo make install
- cd
- cd mosquitto-1.3.5
- cd mosquitto-auth-plug
- cp config.mk.in config.mk
- sudo nano config.mk
- change this line
    MOSQUITTO_SRC = /home/pi/mosquitto-1.3.5
    OPENSSLDIR = /usr/local/openssl
- Ctrl+O + Enter //save
- Ctrl+X //exit out of the file
- make
- gcc -I/home/pi/mosquitto-1.3.5/src/ -I/home/pi/mosquitto-1.3.5/lib/ -fPIC -Wall -Werror -DBE_MYSQL `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/local/openssl/include np.c base64.o -o np -L/usr/local/openssl/lib -lcrypto -ldl
- make
- sudo mv auth-plug.so /etc/mosquitto
- sudo mv /etc/mosquitto/mosquitto.conf.example /etc/mosquitto/mosquitto.conf
- sudo nano /etc/mosquitto/mosquitto.conf
- Ctrl+W //search
- search for auth_plugin and write below mentioned commands after the second occurance of auth_plugin
    auth_plugin /etc/mosquitto/auth-plug.so
    auth_opt_backends mysql
    auth_opt_redis_host localhost
    auth_opt_redis_port 12885
    auth_opt_host localhost
    auth_opt_port 3306
    auth_opt_dbname HAC
    auth_opt_user mqtt_user
    auth_opt_pass ###YOUR_PASSWORD###
    auth_opt_userquery SELECT pw FROM mqtt_users WHERE username = '%s'
    auth_opt_superquery SELECT COUNT(*) FROM mqtt_users WHERE username = '%s' AND super = 1
    auth_opt_aclquery SELECT topic FROM mqtt_acls WHERE (username = '%s') AND (rw >= %d)
    auth_opt_anonusername AnonymouS
- Ctrl+O + Enter //save
- Ctrl+X //Exit out of the file

I have also tried the ldd commands that you suggested and here are the results for each of them:

For: ldd /etc/mosquitto/auth-plug.so

        linux-vdso.so.1 (0x7efe6000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76f07000)
	libmysqlclient.so.18 => /usr/lib/arm-linux-gnueabihf/libmysqlclient.so.18 (0x76be5000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76bbd000)
	libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0x76b96000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76b1b000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76b08000)
	libcrypto.so.1.0.0 => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0 (0x76999000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76858000)
	libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x7677c000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x7674f000)
	/lib/ld-linux-armhf.so.3 (0x54b45000)

For: ldd /usr/local/sbin/mosquitto
        
        linux-vdso.so.1 (0x7ebeb000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76f5c000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76f36000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76ebb000)
	librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0x76ea4000)
	libssl.so.1.0.0 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0 (0x76e4a000)
	libcrypto.so.1.0.0 => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0 (0x76cdc000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76b9a000)
	/lib/ld-linux-armhf.so.3 (0x54b2a000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76b72000)

**Comment by Vishal1419** [comment]
Is there anybody to answer this question??

**Comment by FernandoGarcia** [comment]
Hi!

I think is missing dependencies to install, try this:

`sudo apt-get install perl-doc uuid-dev bsdutils gcc g++ git make dialog libssl-dev libc-ares-dev libcurl4-openssl-dev libmysqlclient-dev libwrap0 libwrap0-dev libwebsockets-dev uthash-dev`

Then try make the plugin again.

Best regards.

**Comment by Vishal1419** [comment]
Thanks for answering but
I tried to make the auth plugin after installing the missing dependencies that you listed above
still I get the same error

**Comment by Vishal1419** [comment]
I have uninstalled mosquitto and installed its latest version. Still getting the same error but its more descriptive this time. Now it says

Load error: /etc/mosquitto/auth-plug.so: undefined symbol:EVP_MD_CTX_reset

**Comment by FernandoGarcia** [comment]
Try this: https://github.com/jpmens/mosquitto-auth-plug/pull/184/files

**Comment by Vishal1419** [comment]
@FernandoGarcia I have tried your suggestion and then I again make auth plugin. Still getting the same error. May be the author @jpmens  know about the symptom of this error.

**Comment by jpmens** [comment]
Should be fixed in #184

**Comment by Vishal1419** [comment]
Still not fixed. I get the same error: undefined symbol: EVP_MD_CTX_reset in auth-plug.so

Now, I am using mosquitto-1.4.11 and openssl-1.1.0e
