### ISSUE TITLE
undefined symbol: EVP_MD_CTX_reset, and #184 didn't work (Mosquitto-1.4.11 and OpenSSL 1.1.0e)

### ISSUE THREAD

**Issue by akdj** [jpmens/mosquitto-auth-plug#205]
I use Mosquitto-1.4.11 and OpenSSL 1.1.0e, with mosquittoo-auth-plug.

And I have this problem when I try to start the mosquitto.service

Note : 
I tried following pr:184 [#184](https://github.com/jpmens/mosquitto-auth-plug/pull/184) but it failed.
Note that my problem is **undefined symbol: EVP_MD_CTX_reset(),** _instead of EVP_MD_CTX_new() and EVP_MD_CTX_free()._ 

Mar 07 08:53:11 sedev systemd[1]: Starting mosquitto mqtt server...
Mar 07 08:53:11 sedev mosquitto_pub[27200]: Warning: Unable to locate configuration directory, default config not loaded.
Mar 07 08:53:11 sedev mosquitto_pub[27200]: Error: Connection refused
Mar 07 08:53:11 sedev systemd[1]: mosquitto.service: control process exited, code=exited status=14
Mar 07 08:53:11 sedev mosquitto[27202]: mosquitto version 1.4.11 (build date 2017-03-02 04:19:45-0500) starting
Mar 07 08:53:11 sedev mosquitto[27202]: Config loaded from /etc/mosquitto/conf.d/mosquitto.conf.
Mar 07 08:53:11 sedev systemd[1]: Failed to start mosquitto mqtt server.
Mar 07 08:53:11 sedev systemd[1]: Unit mosquitto.service entered failed state.
Mar 07 08:53:11 sedev systemd[1]: mosquitto.service failed.
Mar 07 08:53:21 sedev systemd[1]: mosquitto.service holdoff time over, scheduling restart.
Mar 07 08:53:21 sedev systemd[1]: Starting mosquitto mqtt server...
Mar 07 08:53:21 sedev mosquitto[27211]: mosquitto version 1.4.11 (build date 2017-03-02 04:19:45-0500) starting
Mar 07 08:53:21 sedev mosquitto[27211]: Config loaded from /etc/mosquitto/conf.d/mosquitto.conf.
Mar 07 08:53:21 sedev mosquitto_pub[27210]: Warning: Unable to locate configuration directory, default config not loaded.
Mar 07 08:53:21 sedev mosquitto[27211]: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
Mar 07 08:53:21 sedev mosquitto[27211]: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: EVP_MD_CTX_reset
Mar 07 08:53:21 sedev systemd[1]: mosquitto.service: main process exited, code=exited, status=1/FAILURE
Mar 07 08:53:21 sedev mosquitto_pub[27210]: Error: Connection refused
Mar 07 08:53:21 sedev systemd[1]: mosquitto.service: control process exited, code=exited status=14
Mar 07 08:53:21 sedev systemd[1]: Failed to start mosquitto mqtt server.
Mar 07 08:53:21 sedev systemd[1]: Unit mosquitto.service entered failed state.
Mar 07 08:53:21 sedev systemd[1]: mosquitto.service failed.

**Comment by jpmens** [comment]
This has been fixed recently; please download new version (git pull) and rebuild plugin.

**Comment by Vishal1419** [comment]
@jpmens Nope. It is not fixed. I have tried it today. So, my original problem still persists, on #197
